    {"bign128", TLSEXT_SIGALG_bign_sign_128,
     NID_belt_hash, SSL_MD_HBELT_IDX,
     NID_bign_pubkey, SSL_PKEY_BIGN,
     NID_bign_with_hbelt, NID_bign_curve256v1, 1},
    {"bign192", TLSEXT_SIGALG_bign_sign_192,
     NID_bash384, SSL_MD_BASH384_IDX,
     NID_bign_pubkey, SSL_PKEY_BIGN,
     NID_bign_with_bash384, NID_bign_curve384v1, 1},
    {"bign256", TLSEXT_SIGALG_bign_sign_256,
     NID_bash512, SSL_MD_BASH512_IDX,
     NID_bign_pubkey, SSL_PKEY_BIGN,
     NID_bign_with_bash512, NID_bign_curve512v1, 1},
    {"bign_with_hbelt", TLSEXT_SIGALG_bign_with_hbelt,
     NID_belt_hash, SSL_MD_HBELT_IDX,
     NID_bign_pubkey, SSL_PKEY_BIGN,
     NID_bign_with_hbelt, NID_bign_curve256v1, 1},
    {"bign_with_bash384", TLSEXT_SIGALG_bign_with_bash384,
     NID_bash384, SSL_MD_BASH384_IDX,
     NID_bign_pubkey, SSL_PKEY_BIGN,
     NID_bign_with_bash384, NID_bign_curve384v1, 1},
    {"bign_with_bash512", TLSEXT_SIGALG_bign_with_bash512,
     NID_bash512, SSL_MD_BASH512_IDX,
     NID_bign_pubkey, SSL_PKEY_BIGN,
     NID_bign_with_bash512, NID_bign_curve512v1, 1},
