    { "bign128",
        NULL, TLSEXT_SIGALG_bign_sign_128,
        NID_belt_hash, SSL_MD_HBELT_IDX,
        NID_bign_pubkey, SSL_PKEY_BIGN,
        NID_bign_with_hbelt, NID_bign_curve256v1, 1, 0,
        TLS1_2_VERSION, 0, DTLS1_2_VERSION, 0},
    { "bign192",
        NULL, TLSEXT_SIGALG_bign_sign_192,
        NID_bash384, SSL_MD_BASH384_IDX,
        NID_bign_pubkey, SSL_PKEY_BIGN,
        NID_bign_with_bash384, NID_bign_curve384v1, 1, 0,
        TLS1_2_VERSION, 0, DTLS1_2_VERSION, 0},
    { "bign256",
        NULL, TLSEXT_SIGALG_bign_sign_256,
        NID_bash512, SSL_MD_BASH512_IDX,
        NID_bign_pubkey, SSL_PKEY_BIGN,
        NID_bign_with_bash512, NID_bign_curve512v1, 1, 0,
        TLS1_2_VERSION, 0, DTLS1_2_VERSION, 0},
    { "bign_with_hbelt",
        NULL, TLSEXT_SIGALG_bign_with_hbelt,
        NID_belt_hash, SSL_MD_HBELT_IDX,
        NID_bign_pubkey, SSL_PKEY_BIGN,
        NID_bign_with_hbelt, NID_bign_curve256v1, 1, 0,
        TLS1_2_VERSION, 0, DTLS1_2_VERSION, 0},
    { "bign_with_bash384",
        NULL, TLSEXT_SIGALG_bign_with_bash384,
        NID_bash384, SSL_MD_BASH384_IDX,
        NID_bign_pubkey, SSL_PKEY_BIGN,
        NID_bign_with_bash384, NID_bign_curve384v1, 1, 0,
        TLS1_2_VERSION, 0, DTLS1_2_VERSION, 0},
    { "bign_with_bash512",
        NULL, TLSEXT_SIGALG_bign_with_bash512,
        NID_bash512, SSL_MD_BASH512_IDX,
        NID_bign_pubkey, SSL_PKEY_BIGN,
        NID_bign_with_bash512, NID_bign_curve512v1, 1, 0,
        TLS1_2_VERSION, 0, DTLS1_2_VERSION, 0},
